### PR TITLE
Update project files for proper compilation.

### PR DESCRIPTION
**Pull request by Elevator89**

### CODE REVIEW

**Comment by b606** [comment]
OK thanks !
Doesn't the GUID need to be different from yours ?

**Comment by b606** [comment]
I get a warning MSB3256 at compile time*, still a bunch of Unity.Engine*.dll in the _Mod/Assamblies, and red errors when loading in RimWorld (errors are below). I can get rid of the RW red errors by copying the LanguageWorker...{dll,pdb} only, but the mod seems to have no effect in the game (tried  'return "Test" + str + "Test";' in the method ToTitleCase()

- iin Monodevelop:
```
/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3256: Aucun assembly n'a été lu dans les listes de composants redistribuables. Impossible de générer une liste d'exclusion de profil TargetFramework.  (MSB3256) (RimWorld_LanguageWorker_French)
```
- in Rimworld log:
```
RimWorld 1.1.2584 rev1009
Fallback handler could not load library /home/besoa/.steam/steam/steamapps/common/RimWorld/./RimWorldLinux_Data/Mono/data-0x7fdd50119270.so
Fallback handler could not load library /home/besoa/.steam/steam/steamapps/common/RimWorld/./RimWorldLinux_Data/Mono/data-0x7fdd508b11b0.so
Fallback handler could not load library /home/besoa/.steam/steam/steamapps/common/RimWorld/./RimWorldLinux_Data/Mono/data-0x7fdd5013eea0.so
Fallback handler could not load library /home/besoa/.steam/steam/steamapps/common/RimWorld/./RimWorldLinux_Data/Mono/data-0x7fdd508fc9c0.so
Fallback handler could not load library /home/besoa/.steam/steam/steamapps/common/RimWorld/./RimWorldLinux_Data/Mono/data-0x7fdd50a02d00.so
Think node RimWorld.ThinkNode_ConditionalMustKeepLyingDown from think tree Animal already has a parent node (Verse.AI.ThinkNode_Priority). This means that it's referenced by more than one think tree (should have been copied instead).
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Think node Verse.AI.ThinkNode_Subtree from think tree Animal already has a parent node (Verse.AI.ThinkNode_Priority). This means that it's referenced by more than one think tree (should have been copied instead).
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Think node Verse.AI.ThinkNode_Subtree from think tree Animal already has a parent node (Verse.AI.ThinkNode_Priority). This means that it's referenced by more than one think tree (should have been copied instead).
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Think node Verse.AI.ThinkNode_Subtree from think tree Animal already has a parent node (Verse.AI.ThinkNode_Priority). This means that it's referenced by more than one think tree (should have been copied instead).
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Think node RimWorld.JobGiver_ReactToCloseMeleeThreat from think tree Animal already has a parent node (Verse.AI.ThinkNode_Priority). This means that it's referenced by more than one think tree (should have been copied instead).
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Think node Verse.AI.ThinkNode_QueuedJob from think tree Animal already has a parent node (Verse.AI.ThinkNode_Priority). This means that it's referenced by more than one think tree (should have been copied instead).
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
etc;
```

**Comment by Elevator89** [comment]
> 
> 
> OK thanks !
> Doesn't the GUID need to be different from yours ?

This solution guid is yours, not mine, I didn't change it. I've just updated framework version of the project

**Comment by Elevator89** [comment]
> but the mod seems to have no effect in the game (tried 'return "Test" + str + "Test";' in the method ToTitleCase()

Did you modify your localization's LanguageInfo.xml? 
In order to make your LanguageWorker work you need to set `languageWorkerClass` to `RimWorld_LanguageWorker_French.LanguageWorker_French`

**Comment by b606** [comment]
The GUID was copied from yours files so I need to change it. I will try to change the LanguageInfo.xml (didn't think about that :+1: )

**Comment by b606** [comment]
It works ! Thanks a lot !

**Comment by Elevator89** [comment]
You are welcome!

**Pull request merged**
